version: '3'
services:
    plex:
        image: plexinc/pms-docker:${PMSTAG}
        restart: unless-stopped
        networks:
            - web
        ports:
            - '${IP_ADDRESS}:32400:32400/tcp'
            - '${IP_ADDRESS}:3005:3005/tcp'
            - '${IP_ADDRESS}:8324:8324/tcp'
            - '${IP_ADDRESS}:32469:32469/tcp'
            - '${IP_ADDRESS}:1900:1900/udp'
            - '${IP_ADDRESS}:32410:32410/udp'
            - '${IP_ADDRESS}:32412:32412/udp'
            - '${IP_ADDRESS}:32413:32413/udp'
            - '${IP_ADDRESS}:32414:32414/udp'
        environment:
            - TZ=${TZ}
            - PLEX_UID=${PUID}
            - PLEX_GID=${PGID}
            - PLEX_CLAIM=${PMSTOKEN}
            - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
            - ALLOWED_NETWORKS=${CIDR_ADDRESS}
        hostname: ${HOSTNAME}
        volumes:
            - './config/plex:/config'
            - '/nfs/mediabot/transcode:/transcode'
            - '/nfs/mediabot/library/movies:/data/movies'
            - '/nfs/mediabot/library/tv:/data/tv'
            - '/nfs/mediabot/library/other:/data/other'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=32400'
            - 'traefik.frontend.rule=Host:plex.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
    transmission:
        image: haugene/transmission-openvpn
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        networks:
            - web
        ports:
            - '${IP_ADDRESS}:9091:9091'
            - '${IP_ADDRESS}:51413:51413'
            - '${IP_ADDRESS}:51413:51413/udp'
        expose:
            - 9091
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_USERNAME=${VPNUNAME}
            - OPENVPN_PASSWORD=${VPNPASS}
            - OPENVPN_CONFIG=sweden
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=${CIDR_ADDRESS}
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_RATIO_LIMIT=1
            - TRANSMISSION_RPC_WHITELIST_ENABLED=false
            - TRANSMISSION_WEB_UI=combustion
            - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true # attempt to fix watch dir…not working
            - OVERRIDE_DNS_1=8.8.8.8
            - OVERRIDE_DNS_2=8.8.4.4
        volumes:
            - '/nfs/mediabot/downloads/completed:/data/completed'
            - '/nfs/mediabot/downloads/incomplete:/data/incomplete'
            - '/nfs/mediabot/downloads/watch:/data/watch'
            - './config/transmission/transmission-home:/data/transmission-home'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=9091'
            - 'traefik.frontend.auth.basic=${TRAEFIK_AUTH}'
            - 'traefik.frontend.rule=Host:transmission.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'
    sonarr:
        image: linuxserver/sonarr
        restart: unless-stopped
        networks:
            - web
        expose:
            - 8989
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - './config/sonarr:/config'
            - '/nfs/mediabot/downloads/completed:/data/completed'
            - '/nfs/mediabot/library/tv:/tv'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=8989'
            - 'traefik.frontend.rule=Host:tv.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'
    radarr:
        image: linuxserver/radarr
        restart: unless-stopped
        networks:
            - web
        expose:
            - 7878
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - './config/radarr:/config'
            - '/nfs/mediabot/downloads/completed:/data/completed'
            - '/nfs/mediabot/library/movies:/movies'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=7878'
            - 'traefik.frontend.rule=Host:movies.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'
    jackett:
        image: linuxserver/jackett
        restart: unless-stopped
        networks:
            - web
        expose:
            - 9117
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - './config/jackett:/config'
            - '/nfs/mediabot/downloads/watch:/downloads'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=9117'
            - 'traefik.frontend.rule=Host:jackett.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'

    # ----------------------------------------
    # WATCHTOWER
    # Automatic Update Service for Docker VMs
    # ----------------------------------------
    watchtower:
        image: v2tec/watchtower
        restart: unless-stopped
        networks:
            - internal
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/ssl/certs:/etc/ssl/certs'
        command: --schedule @midnight --cleanup
        labels:
            - 'traefik.enable=false'

    # ----------------------------------------
    # Heimdall
    # Web dashboard
    # ----------------------------------------
    heimdall:
        image: linuxserver/heimdall
        restart: unless-stopped
        networks:
            - web
        expose:
            - 80
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - './config/heimdall:/config'
            - '/etc/localtime:/etc/localtime:ro'
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=80'
            - 'traefik.frontend.rule=Host:${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'

    # ----------------------------------------
    # TRAEFIK
    # Reverse Proxy + SSL Support
    # ----------------------------------------
    traefik:
        image: traefik:v1.7.16
        restart: unless-stopped
        networks:
            - web
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './config/traefik:/etc/traefik/acme'
        command:
            - --docker
            - --api
            - --loglevel=debug
            - "--entryPoints=Name:https Address::443 TLS"
            - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
            - --acme.entrypoint=https
            - --acme=true
            - --acme.domains=${DOMAIN}
            - --acme.email=${EMAIL}
            - --acme.ondemand=true
            - --acme.onhostrule
            - --acme.httpchallenge
            - --acme.httpchallenge.entrypoint=http
            - --acme.storage=etc/traefik/acme/acme.json
            - --docker.watch
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${STACK_NAME}_web'
            - 'traefik.port=8080'
            - 'traefik.frontend.rule=Host:traefik.${DOMAIN}'
            - 'traefik.frontend.entryPoints=https'
            - 'traefik.frontend.auth.basic=${TRAEFIK_AUTH}'
            - 'traefik.frontend.headers.forceSTSHeader=true'
            - 'traefik.frontend.headers.STSSeconds=315360000'
            - 'traefik.frontend.headers.STSIncludeSubdomains=true'
            - 'traefik.frontend.headers.STSPreload=true'
networks:
    internal:
    web:
